### PR TITLE
Upgrade sqlx to 0.7

### PR DESCRIPTION
**Pull request by qwfy**
Nothing fancy, just upgraded sqlx to 0.7, and some minor changes.

### CODE REVIEW

**Comment by geofmureithi** [comment]
Thanks!
This will also close #121

**Comment by IgnisDa** [comment]
@geofmureithi Any updates on this?

**Comment by geofmureithi** [comment]
It needs some cleaning up. I am thinking of releasing on v0.5.
Is it blocking you on something specific?

**Comment by IgnisDa** [comment]
Yes I want to upgrade `sea-orm` in my project which also depends on sqlx 0.7.

> I am thinking of releasing on v0.5.

That's fine. I can wait till then. Any specific ETA?

**Comment by geofmureithi** [comment]
I am hoping to work on some of these issues over the weekend. I can try and release an alpha version so that it can unblock you.
Let me see what I can get done.

**Pull request closed without merging**
